package ai

import (
	"math/rand/v2"
)

var loaderMessages = []string{
	"thinking…",
	"processing…",
	"working on it…",
	"figuring it out…",
	"analyzing…",
	"computing…",
	"looking into it…",
	"evaluating options…",
	"searching for the right command…",
	"putting it together…",
	"almost there…",
	"just a moment…",
	"crunching…",
	"parsing your request…",
	"on it…",
	"loading brain cells…",
	"assembling the command…",
	"cooking something up…",
	"running the numbers…",
	"connecting the dots…",

	"hang tight…",
	"one sec…",
	"give me a moment…",
	"working my magic…",
	"i got you…",
	"let me handle this…",
	"coming right up…",
	"you're in good hands…",
	"brb with something good…",
	"let me think about this…",
	"hold that thought…",
	"i'm on the case…",
	"pulling some strings…",
	"let me work my charm…",
	"crafting the perfect command…",
	"brewing your command…",
	"mixing the ingredients…",
	"preparing your order…",
	"rolling up my sleeves…",
	"getting my hands dirty…",

	"discombobulating…",
	"reticulating splines…",
	"consulting the oracle…",
	"asking the magic 8-ball…",
	"summoning the shell gods…",
	"interrogating the terminal…",
	"bribing the cpu…",
	"negotiating with the kernel…",
	"feeding the hamsters…",
	"warming up the flux capacitor…",
	"polishing the bits…",
	"herding electrons…",
	"untangling spaghetti…",
	"defragmenting my thoughts…",
	"rebooting my imagination…",
	"downloading more ram…",
	"asking jeeves…",
	"consulting stackoverflow…",
	"googling furiously…",
	"flipping through the manual…",
	"phoning a friend…",
	"rolling a d20 for intelligence…",
	"sacrificing a semicolon…",
	"compiling thoughts…",
	"garbage collecting my ideas…",
	"malloc-ing brain space…",
	"sudo thinking…",
	"chmod +x brain…",
	"piping thoughts to stdout…",
	"grep-ing for answers…",
	"awk-wardly thinking…",

	"performing dark arts…",
	"reverse engineering your intent…",
	"translating human to shell…",
	"channeling my inner unix wizard…",
	"consulting the man pages of my soul…",
	"decoding your vibe…",
	"converting caffeine to commands…",
	"applying machine yearning…",
	"doing science…",
	"constructing additional pylons…",
	"hacking the mainframe…",
	"entering the matrix…",
	"following the white rabbit…",
	"bending spoons…",
	"dividing by zero (carefully)…",
	"solving p=np real quick…",
	"counting to infinity…",
	"finding the any key…",
	"turning it off and on again…",
	"reading the source code of the universe…",

	"traversing the solution space…",
	"optimizing for your use case…",
	"running inference…",
	"resolving dependencies…",
	"mapping the command graph…",
	"cross-referencing possibilities…",
	"validating approach vectors…",
	"synthesizing the optimal path…",
	"contextualizing your request…",
	"performing lexical analysis…",
	"building the abstract syntax tree…",
	"reducing cognitive overhead…",
	"indexing potential solutions…",
	"pruning the decision tree…",
	"calibrating confidence intervals…",
	"normalizing the output…",
	"vectorizing your intent…",
	"backpropagating through options…",
	"gradient descending toward an answer…",
	"tokenizing your thoughts…",

	"may i help you? yes i may…",
	"may the command be with you…",
	"may-be this will work…",
	"may-king a suggestion…",
	"may-nifesting the right command…",
	"may day, may day, processing…",
	"it may take a moment…",
	"may-pping your intent to shell…",
	"may-lding the perfect command…",
	"may-triculating…",
	"may-be i'm overthinking this…",
	"may-sterfully crafting…",
	"you may want to sit down for this…",
	"may-hem in progress…",
	"come what may…",
}

var loaderIndex int

func nextLoaderMessage() string {
	if loaderIndex == 0 {
		rand.Shuffle(len(loaderMessages), func(i, j int) {
			loaderMessages[i], loaderMessages[j] = loaderMessages[j], loaderMessages[i]
		})
	}

	msg := loaderMessages[loaderIndex%len(loaderMessages)]
	loaderIndex++
	return msg
}
